default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: paulamespindola
  password: root
  port: 5432

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: to_do_development

test:
  <<: *default
  database: to_do_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  
# production:
#   <<: *default
#   database: dbaba
#   username: dbaba_user
#   password: <%= ENV["ABA_NETWORK_DATABASE_PASSWORD"] %>